### PR TITLE
add linux build support

### PR DESCRIPTION
**Pull request by lersi**
added linux build support for Github CI

Co-authored-by: lersi <liorshalmay1@gmail.com>

### CODE REVIEW

**Comment by xCuri0** [comment]
Path ```${{github.workspace}}/Build/ReBarUEFI/RELEASE_VS2019/X64/ReBarDxe.ffs``` needs to be changed to ```${{github.workspace}}/Build/ReBarUEFI/RELEASE_GCC5/X64/ReBarDxe.ffs```. Besides that it appears to work without issues

**Comment by lersi** [comment]
whoops, fixed that

**Comment by xCuri0** [comment]
@lersi looks good squash commits and i will merge.

**Review by xCuri0 — APPROVED** [review]

**Comment by lersi** [comment]
I have squashed the commits

**Pull request merged**
